networks:
  ticketz:
  nginx-proxy:

volumes:
  ngx_conf:
  ngx_vhost:
  ngx_html:
  ngx_dhparam:
  ngx_certs:
  ngx_acme:
  redis_data:
  postgres_data:
  backend_public:
  backend_private:
    
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ticketz-nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ngx_conf:/etc/nginx/conf.d
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam
      - ngx_certs:/etc/nginx/certs:ro
      - ./confs/nginx-ticketz.conf:/etc/nginx/conf.d/ticketz.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: ticketz-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam:ro
      - ngx_certs:/etc/nginx/certs
      - ngx_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=ticketz-nginx-proxy
    networks:
      - nginx-proxy

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    env_file:
      - .env-backend-prod
    environment:
      - VIRTUAL_HOST=whatsapp.mercteste.live
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=whatsapp.mercteste.live
      - LETSENCRYPT_EMAIL=admin@mercteste.live
    restart: always
    depends_on:
      - acme-companion
      - postgres
      - redis
    networks:
      - ticketz
      - nginx-proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env-frontend-prod
    volumes:
      - backend_public:/var/www/backend-public/      
    environment:
      - VIRTUAL_HOST=whatsapp.mercteste.live
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=whatsapp.mercteste.live
      - LETSENCRYPT_EMAIL=admin@mercteste.live
    restart: always
    depends_on:
      - acme-companion
      - backend
    networks:
      - ticketz
      - nginx-proxy

  postgres:
    image: postgres:16-alpine
    container_name: ticketz-postgres
    restart: always
    environment:
      POSTGRES_DB: ticketz
      POSTGRES_USER: ticketz
      POSTGRES_PASSWORD: ticketz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketz

  redis:
    image: redis:alpine
    container_name: ticketz-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - ticketz

  pgadmin4:
    image: dpage/pgadmin4:8
    container_name: ticketz-pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mercteste.live
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ticketz
    ports:
      - "8081:80"

volumes:
  pgadmin_data:
